---
# tasks file for db
- name: Install Dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items:
    - mariadb-server
    - python3-pymysql
- name: Create Database
  community.mysql.mysql_db:
    name: dbmovie
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
- name: Create DB user
  community.mysql.mysql_user:
    name: movie
    host: '%'
    password: password
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
- name: Listen on all network interfaces
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: bind-address = 0.0.0.0
  register: result
    
- name: Restart MariaDB server
  ansible.builtin.systemd:
    name: mariadb
    state: restarted
  when: result is changed  
